# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "AI Dance Feedback App Portfolio"
description: "A research portfolio exploring AI-based dance fundamental training and real-time feedback systems, integrating pose estimation, motion analysis, and prototype development.
"
url: "https://heeddobbak.github.io"
email: "heeddobbak@gmail.com"
github: "heeddobbak"
name:      "Heeseon Choi"
